Repository mitodl/learn-ai, pull requests merged in 2025-03, with the labels that each got.

#82 tutorbot front end
  ai_chatbots/urls.py
  ai_chatbots/views.py
  ai_chatbots/views_test.py
  frontend-demo/api/src/generated/v0/api.ts
  frontend-demo/package.json
  frontend-demo/src/app/page.tsx
  frontend-demo/src/app/tutor/page.tsx
  frontend-demo/src/app/utils.tsx
  frontend-demo/yarn.lock
  main/settings.py
  openapi/specs/v0.yaml
Labels: waiting on author

#85 add git hash to docker images
  Dockerfile
Labels: Needs Review

#87 fix git hash path
  Dockerfile
Labels: Needs Review

#84 Object-specific cookies; refactored cookie management
  ai_chatbots/chatbots.py
  ai_chatbots/checkpointers.py
  ai_chatbots/constants.py
  ai_chatbots/consumers.py
  ai_chatbots/consumers_test.py
  ai_chatbots/migrations/0004_userchatsession_more_fields.py
  ai_chatbots/models.py
  ai_chatbots/tasks.py
  ai_chatbots/tasks_test.py
  main/settings.py
  main/utils.py
Labels: waiting on author

#89 Make sentry work for asgi endpoints too
  main/asgi.py
Labels: Needs Review

#106 Litellm Compose Service Fix
  Dockerfile-litellm
  docker-compose.services.yml
  docker-compose.yml
Labels: waiting on author, Needs Review

#101 Add OpenTelemetry Config
  main/apps.py
  main/settings.py
  main/telemetry.py
  poetry.lock
  pyproject.toml
Labels: Work in Progress

#113 use edx module to get the problem
  ai_chatbots/chatbots.py
  ai_chatbots/chatbots_test.py
  ai_chatbots/consumers.py
  ai_chatbots/consumers_test.py
  ai_chatbots/serializers.py
  frontend-demo/package.json
  frontend-demo/src/app/tutor/page.tsx
  frontend-demo/yarn.lock
  main/settings.py
  poetry.lock
  pyproject.toml
Labels: waiting on author
