Repository mitodl/learn-ai, pull requests merged in 2025-04, with the labels that each got.

#115 Do not update sessions assigned to another user
  ai_chatbots/consumers.py
  ai_chatbots/consumers_test.py
Labels: Needs Review

#124 LLM models API endpoint for playground
  ai_chatbots/admin.py
  ai_chatbots/factories.py
  ai_chatbots/fixtures/initial_llm_models.json
  ai_chatbots/migrations/0005_llmmodel.py
  ai_chatbots/models.py
  ai_chatbots/serializers.py
  ai_chatbots/urls.py
  ai_chatbots/views.py
  ai_chatbots/views_test.py
  env/backend.local.example.env
  frontend-demo/api/src/generated/v0/api.ts
  main/settings.py
  openapi/specs/v0.yaml
  poetry.lock
  pyproject.toml
Labels: Needs Review

#122 Chat request limits for users
  ai_chatbots/consumers.py
  ai_chatbots/consumers_test.py
  env/backend.env
  main/admin.py
  main/apps.py
  main/constants.py
  main/consumer_throttles.py
  main/consumer_throttles_test.py
  main/consumers.py
  main/consumers_test.py
  main/exceptions.py
  main/factories.py
  main/migrations/0001_initial.py
  main/migrations/__init__.py
  main/models.py
  main/settings.py
  main/utils.py
Labels: Needs Review

#126 refactor open_learning_ai_tutor
  ai_chatbots/chatbots.py
  ai_chatbots/chatbots_test.py
  poetry.lock
  pyproject.toml
Labels: waiting on author

#141 Frontend sandbox for ai testing
  .github/workflows/ci.yml
  .github/workflows/production-deploy.yml
  .github/workflows/rc-deploy.yml
  docker-compose.apps.yml
  env/frontend.env
  frontend-demo/dev-proxy-server.js
  frontend-demo/next.config.ts
  frontend-demo/package.json
  frontend-demo/src/app/(home)/AssessmentContent.tsx
  frontend-demo/src/app/(home)/ChatTabs.tsx
  frontend-demo/src/app/(home)/OpenedxLoginAlert.tsx
  frontend-demo/src/app/(home)/OpenedxUnitSelectionForm.tsx
  frontend-demo/src/app/(home)/RecommendationContent.tsx
  frontend-demo/src/app/(home)/SelectModel.tsx
  frontend-demo/src/app/(home)/StyledAiChat.tsx
  frontend-demo/src/app/(home)/SyllabusContent.tsx
  frontend-demo/src/app/(home)/VideoContent.tsx
  frontend-demo/src/app/(home)/page.tsx
  frontend-demo/src/app/(home)/util.ts
  frontend-demo/src/app/layout.tsx
  frontend-demo/src/app/page.tsx
  frontend-demo/src/app/providers.tsx
  frontend-demo/src/app/tutor/page.tsx
  frontend-demo/src/components/Header/Header.tsx
  frontend-demo/src/constants.ts
  frontend-demo/src/services/ai/index.ts
  frontend-demo/src/services/ai/llm-models/queries.ts
  frontend-demo/src/services/ai/settings.ts
  frontend-demo/src/services/ai/urls.ts
  frontend-demo/src/services/ai/user/queries.ts
  frontend-demo/src/services/learn/contentfiles/queries.ts
  frontend-demo/src/services/learn/index.ts
  frontend-demo/src/services/learn/learning-resources/queries.ts
  frontend-demo/src/services/learn/settings.ts
  frontend-demo/src/services/openedx/client.ts
  frontend-demo/src/services/openedx/index.ts
  frontend-demo/src/services/openedx/queries.ts
  frontend-demo/tsconfig.json
  frontend-demo/yarn.lock
  main/settings.py
Labels: waiting on author

#152 fix two trailing slash issues
  frontend-demo/src/services/ai/user/queries.ts
  frontend-demo/src/services/openedx/client.ts
Labels: waiting on author

#153 Make gemini optional by request
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: waiting on author

#150 Clear throttle cache on ConsumerThrottleLimit.save
  main/constants.py
  main/consumer_throttles.py
  main/models.py
  main/models_test.py
Labels: Needs Review

#158 add ci env vars
  .github/workflows/ci-deploy.yml
Labels: waiting on author

#157 Option to override the default recommendation bot search url
  ai_chatbots/api.py
  ai_chatbots/chatbots.py
  ai_chatbots/chatbots_test.py
  ai_chatbots/consumers.py
  ai_chatbots/consumers_test.py
  ai_chatbots/factories.py
  ai_chatbots/serializers.py
  ai_chatbots/tools.py
  ai_chatbots/tools_test.py
  env/frontend.env
  env/shared.env
  frontend-demo/src/app/(home)/RecommendationContent.tsx
  frontend-demo/src/app/(home)/SelectSearchUrl.tsx
  frontend-demo/src/app/(home)/util.ts
  main/settings.py
Labels: waiting on author, Needs Review
