Repository mitodl/learn-ai, pull requests merged in 2025-06, with the labels that each got.

#205 Enable the recommendation bot to search for specific resource details
  ai_chatbots/api.py
  ai_chatbots/api_test.py
  ai_chatbots/chatbots.py
  ai_chatbots/chatbots_test.py
  ai_chatbots/prompts.py
  ai_chatbots/tools.py
Labels: waiting on author

#206 Syllabus bot for programs
  ai_chatbots/chatbots.py
  ai_chatbots/consumers.py
  ai_chatbots/serializers.py
  ai_chatbots/tools.py
  frontend-demo/package.json
  frontend-demo/src/app/(home)/SyllabusContent.tsx
  frontend-demo/src/services/learn/contentfiles/queries.ts
  frontend-demo/src/services/learn/learning-resources/queries.ts
  frontend-demo/yarn.lock
Labels: Work in Progress

#210 Change default env values for agent models, search url
  main/settings.py
Labels: Needs Review

#215 one word change to video prompt
  ai_chatbots/prompts.py
Labels: waiting on author

#218 AI system prompts endpoint
  ai_chatbots/chatbots.py
  ai_chatbots/management/commands/clear_prompt_cache.py
  ai_chatbots/management/commands/update_prompt.py
  ai_chatbots/prompts.py
  ai_chatbots/prompts_test.py
  ai_chatbots/serializers.py
  ai_chatbots/urls.py
  ai_chatbots/views.py
  ai_chatbots/views_test.py
  env/backend.env
  frontend-demo/api/src/generated/v0/api.ts
  frontend-demo/src/app/(home)/AssessmentContent.tsx
  frontend-demo/src/app/(home)/BaseChatContent.tsx
  frontend-demo/src/app/(home)/RecommendationContent.tsx
  frontend-demo/src/app/(home)/SelectPrompt.tsx
  frontend-demo/src/app/(home)/SyllabusContent.tsx
  frontend-demo/src/app/(home)/VideoContent.tsx
  frontend-demo/src/services/ai/index.ts
  frontend-demo/src/services/ai/prompts/queries.ts
  frontend-demo/src/services/ai/user/queries.ts
  openapi/specs/v0.yaml
Labels: Needs Review

#224 limit message length
  ai_chatbots/serializers.py
  ai_chatbots/serializers_test.py
  main/settings.py
Labels: waiting on author
